import { publicProcedure, protectedProcedure, ownerProcedure, adminProcedure, router } from "../_core/trpc";
import { z } from "zod";
import * as db from "../db";
import { TRPCError } from "@trpc/server";

export const centresRouter = router({
  list: publicProcedure.query(async ({ ctx }) => {
    return await db.getShoppingCentres(ctx.tenantOwnerId ?? undefined);
  }),
  
  search: publicProcedure
    .input(z.object({ query: z.string() }))
    .query(async ({ input, ctx }) => {
      return await db.searchShoppingCentres(input.query, undefined, ctx.tenantOwnerId ?? undefined);
    }),
  
  getById: publicProcedure
    .input(z.object({ id: z.number() }))
    .query(async ({ input, ctx }) => {
      const centre = await db.getShoppingCentreById(input.id);
      if (!centre) throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      if (ctx.tenantOwnerId && centre.ownerId !== ctx.tenantOwnerId) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      }
      return centre;
    }),
  getBySlug: publicProcedure
    .input(z.object({ slug: z.string() }))
    .query(async ({ input, ctx }) => {
      const centre = await db.getShoppingCentreBySlug(input.slug);
      if (!centre) throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      if (ctx.tenantOwnerId && centre.ownerId !== ctx.tenantOwnerId) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      }
      return centre;
    }),
  getBySlugOrId: publicProcedure
    .input(z.object({ idOrSlug: z.string() }))
    .query(async ({ input, ctx }) => {
      const centre = await db.getShoppingCentreByIdOrSlug(input.idOrSlug);
      if (!centre) throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      if (ctx.tenantOwnerId && centre.ownerId !== ctx.tenantOwnerId) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      }
      return centre;
    }),
  getSites: publicProcedure
    .input(z.object({ centreId: z.number() }))
    .query(async ({ input, ctx }) => {
      if (ctx.tenantOwnerId) {
        const centre = await db.getShoppingCentreById(input.centreId);
        if (!centre || centre.ownerId !== ctx.tenantOwnerId) {
          throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
        }
      }
      return await db.getSitesByCentreId(input.centreId);
    }),
  
  getByState: publicProcedure
    .input(z.object({ state: z.string().trim().toUpperCase() }))
    .query(async ({ input, ctx }) => {
      return await db.getShoppingCentresByState(input.state, ctx.tenantOwnerId ?? undefined);
    }),
  
  getNearby: publicProcedure
    .input(z.object({ 
      centreId: z.number(),
      radiusKm: z.number().optional().default(10),
    }))
    .query(async ({ input, ctx }) => {
      const nearby = await db.getNearbyCentres(input.centreId, input.radiusKm, ctx.tenantOwnerId ?? undefined);
      if (nearby.length > 0) return { centres: nearby, nearest: [] };
      // No centres within radius — return the 3 closest centres regardless of distance
      const allNearby = await db.getNearbyCentres(input.centreId, 9999, ctx.tenantOwnerId ?? undefined);
      return { centres: [], nearest: allNearby.slice(0, 3) };
    }),

  getFloorLevels: publicProcedure
    .input(z.object({ centreId: z.number() }))
    .query(async ({ input, ctx }) => {
      if (ctx.tenantOwnerId) {
        const centre = await db.getShoppingCentreById(input.centreId);
        if (!centre || centre.ownerId !== ctx.tenantOwnerId) {
          throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
        }
      }
      return await db.getFloorLevelsByCentre(input.centreId);
    }),
  
  listWithCodes: ownerProcedure.query(async ({ ctx }) => {
    const { generateAbbreviatedCentreCode } = await import('../centreCodeHelper');
    const { getScopedOwnerId } = await import('../tenantScope');
    const scopedOwnerId = getScopedOwnerId(ctx.user);
    const centres = await db.getShoppingCentres(scopedOwnerId ?? undefined);
    
    return centres.map(centre => ({
      id: centre.id,
      name: centre.name,
      currentCode: centre.centreCode,
      autoGeneratedCode: generateAbbreviatedCentreCode(centre.name),
      state: centre.state,
      city: centre.city,
    }));
  }),
  
  updateCentreCode: adminProcedure
    .input(z.object({
      centreId: z.number(),
      centreCode: z.string().length(4).regex(/^[A-Z]{4}$/, 'Code must be 4 uppercase letters'),
    }))
    .mutation(async ({ input }) => {
      // Check if code is already used by another centre
      const centres = await db.getShoppingCentres();
      const existing = centres.find(c => 
        c.centreCode === input.centreCode && c.id !== input.centreId
      );
      
      if (existing) {
        throw new TRPCError({ 
          code: 'BAD_REQUEST', 
          message: `Code ${input.centreCode} is already used by ${existing.name}` 
        });
      }
      
      await db.updateShoppingCentre(input.centreId, { 
        centreCode: input.centreCode 
      });
      
      return { success: true };
    }),
  
  update: ownerProcedure
    .input(z.object({
      id: z.number(),
      name: z.string().trim().min(1).optional(),
      address: z.string().trim().optional(),
      suburb: z.string().trim().optional(),
      state: z.string().trim().toUpperCase().optional(),
      postcode: z.string().trim().optional(),
      description: z.string().optional(),
      contactPhone: z.string().trim().optional(),
      contactEmail: z.string().email().optional(),
      operatingHours: z.string().optional(),
      policies: z.string().optional(),
      pdfUrl1: z.string().optional(),
      pdfName1: z.string().optional(),
      pdfUrl2: z.string().optional(),
      pdfName2: z.string().optional(),
      pdfUrl3: z.string().optional(),
      pdfName3: z.string().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const { getScopedOwnerId } = await import('../tenantScope');
      const scopedOwnerId = getScopedOwnerId(ctx.user);
      const centre = await db.getShoppingCentreById(input.id);
      if (!centre) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      }
      if (scopedOwnerId && centre.ownerId !== scopedOwnerId) {
        throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
      }
      
      // Update centre
      await db.updateShoppingCentre(input.id, input);
      
      // Refresh location index and search cache when location-relevant fields change
      if (input.name || input.suburb || input.state || input.postcode) {
        import("../locationIndex").then(m => m.refreshLocationIndex()).catch(() => {});
        import("../searchCache").then(m => m.clearSearchCache()).catch(() => {});
      }
      
      import("../auditHelper").then(m => m.writeAudit({
        userId: ctx.user.id,
        action: "centre_updated",
        entityType: "centre",
        entityId: input.id,
        changes: input,
      })).catch(() => {});
      
      return { success: true, message: "Centre updated successfully" };
    }),
  
  uploadPdf: ownerProcedure
    .input(z.object({
      centreId: z.number(),
      slot: z.number().min(1).max(3),
      base64Pdf: z.string(),
      originalName: z.string(),
    }))
    .mutation(async ({ input, ctx }) => {
      const { getScopedOwnerId } = await import('../tenantScope');
      const scopedOwnerId = getScopedOwnerId(ctx.user);
      if (scopedOwnerId) {
        const centre = await db.getShoppingCentreById(input.centreId);
        if (!centre || centre.ownerId !== scopedOwnerId) {
          throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
        }
      }
      const { storagePut } = await import('../storage');
      
      // Extract base64 data
      const base64Data = input.base64Pdf.replace(/^data:application\/pdf;base64,/, '');
      const buffer = Buffer.from(base64Data, 'base64');
      
      // Generate unique filename
      const timestamp = Date.now();
      const randomSuffix = Math.random().toString(36).substring(2, 8);
      const safeOriginalName = input.originalName.replace(/[^a-zA-Z0-9.-]/g, '_');
      const fileKey = `centres/${input.centreId}/pdfs/pdf${input.slot}-${timestamp}-${randomSuffix}-${safeOriginalName}`;
      
      // Upload to S3
      const { url } = await storagePut(fileKey, buffer, 'application/pdf');
      
      return { url, originalName: input.originalName };
    }),
  
  updateWeeklyReportSettings: ownerProcedure
    .input(z.object({
      id: z.number(),
      weeklyReportEmail1: z.string().email().nullable().optional(),
      weeklyReportEmail2: z.string().email().nullable().optional(),
      weeklyReportEmail3: z.string().email().nullable().optional(),
      weeklyReportEmail4: z.string().email().nullable().optional(),
      weeklyReportEmail5: z.string().email().nullable().optional(),
      weeklyReportEmail6: z.string().email().nullable().optional(),
      weeklyReportEmail7: z.string().email().nullable().optional(),
      weeklyReportEmail8: z.string().email().nullable().optional(),
      weeklyReportEmail9: z.string().email().nullable().optional(),
      weeklyReportEmail10: z.string().email().nullable().optional(),
      weeklyReportTimezone: z.string().optional(),
      weeklyReportNextOverrideDay: z.enum(["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]).nullable().optional(),
    }))
    .mutation(async ({ input, ctx }) => {
      const { getScopedOwnerId } = await import('../tenantScope');
      const scopedOwnerId = getScopedOwnerId(ctx.user);
      const centre = await db.getShoppingCentreById(input.id);
      if (!centre) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Centre not found" });
      }
      if (scopedOwnerId && centre.ownerId !== scopedOwnerId) {
        throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
      }
      
      await db.updateShoppingCentre(input.id, input);
      return { success: true, message: "Weekly report settings updated successfully" };
    }),
  
  geocodeAll: adminProcedure
    .mutation(async () => {
      const centres = await db.getShoppingCentres();
      const missing = centres.filter(
        (c) => !c.latitude || !c.longitude || c.latitude === "0" || c.longitude === "0",
      );

      const results: Array<{ id: number; name: string; success: boolean; error?: string }> = [];

      async function nominatimSearch(query: string): Promise<{ lat: string; lon: string } | null> {
        const url = new URL("https://nominatim.openstreetmap.org/search");
        url.searchParams.set("q", query);
        url.searchParams.set("format", "json");
        url.searchParams.set("limit", "1");
        url.searchParams.set("countrycodes", "au");

        const res = await fetch(url.toString(), {
          headers: { "User-Agent": "CasualLease/1.0" },
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);

        const data = await res.json() as Array<{ lat: string; lon: string }>;
        await new Promise((r) => setTimeout(r, 1100));
        return data.length > 0 ? data[0] : null;
      }

      for (const centre of missing) {
        // Try multiple search strategies in order of specificity
        const queries = [
          [centre.name, centre.address, centre.suburb, centre.state, centre.postcode].filter(Boolean).join(", "),
          [centre.name, centre.suburb, centre.state].filter(Boolean).join(", "),
          [centre.address, centre.suburb, centre.state].filter(Boolean).join(", "),
          [centre.suburb, centre.state, "Australia"].filter(Boolean).join(", "),
        ];

        try {
          let found = false;
          for (const query of queries) {
            if (!query.trim()) continue;
            const result = await nominatimSearch(query);
            if (result) {
              await db.updateShoppingCentre(centre.id, {
                latitude: result.lat,
                longitude: result.lon,
              });
              results.push({ id: centre.id, name: centre.name, success: true });
              found = true;
              break;
            }
          }
          if (!found) {
            results.push({ id: centre.id, name: centre.name, success: false, error: "No results for any query variation" });
          }
        } catch (err: any) {
          results.push({ id: centre.id, name: centre.name, success: false, error: err.message });
        }
      }

      return { total: centres.length, geocoded: results.filter((r) => r.success).length, failed: results.filter((r) => !r.success).length, results };
    }),

  sendTestWeeklyReport: ownerProcedure
    .input(z.object({ centreId: z.number() }))
    .mutation(async ({ input, ctx }) => {
      const { getScopedOwnerId } = await import('../tenantScope');
      const scopedOwnerId = getScopedOwnerId(ctx.user);
      if (scopedOwnerId) {
        const centre = await db.getShoppingCentreById(input.centreId);
        if (!centre || centre.ownerId !== scopedOwnerId) {
          throw new TRPCError({ code: "FORBIDDEN", message: "Access denied" });
        }
      }
      const { triggerWeeklyReport } = await import("../reportScheduler");
      const result = await triggerWeeklyReport(input.centreId);
      
      if (!result.success) {
        throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: result.message });
      }
      
      return { success: true, message: "Test report sent successfully" };
    }),
});
