import { useState } from 'react';
import { trpc } from '@/lib/trpc';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { Pencil, Check, X, Loader2 } from 'lucide-react';

export default function CentreCodes() {
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editValue, setEditValue] = useState('');

  const { data: centres, isLoading, refetch } = trpc.centres.listWithCodes.useQuery();
  const updateCode = trpc.centres.updateCentreCode.useMutation({
    onSuccess: () => {
      toast.success('Centre code updated successfully');
      refetch();
      setEditingId(null);
      setEditValue('');
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to update centre code');
    },
  });

  const handleEdit = (centre: { id: number; currentCode: string | null; autoGeneratedCode: string }) => {
    setEditingId(centre.id);
    setEditValue(centre.currentCode || centre.autoGeneratedCode);
  };

  const handleSave = (centreId: number) => {
    const trimmed = editValue.trim().toUpperCase();
    
    if (trimmed.length !== 4) {
      toast.error('Code must be exactly 4 characters');
      return;
    }
    
    if (!/^[A-Z]{4}$/.test(trimmed)) {
      toast.error('Code must contain only uppercase letters');
      return;
    }

    updateCode.mutate({ centreId, centreCode: trimmed });
  };

  const handleCancel = () => {
    setEditingId(null);
    setEditValue('');
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="container py-8">
      <Card>
        <CardHeader>
          <CardTitle>Centre Code Management</CardTitle>
          <CardDescription>
            Manage 4-letter codes for each shopping centre. These codes are used in booking numbers (e.g., CAMA-20260601-001).
            You can use the auto-generated code or customize it for branding consistency.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Centre Name</TableHead>
                <TableHead>Location</TableHead>
                <TableHead>Current Code</TableHead>
                <TableHead>Auto-Generated</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {centres?.map((centre) => (
                <TableRow key={centre.id}>
                  <TableCell className="font-medium">{centre.name}</TableCell>
                  <TableCell className="text-muted-foreground">
                    {centre.city}, {centre.state}
                  </TableCell>
                  <TableCell>
                    {editingId === centre.id ? (
                      <Input
                        value={editValue}
                        onChange={(e) => setEditValue(e.target.value.toUpperCase())}
                        maxLength={4}
                        className="w-24 font-mono uppercase"
                        placeholder="CODE"
                        autoFocus
                      />
                    ) : (
                      <Badge variant="secondary" className="font-mono text-sm">
                        {centre.currentCode || centre.autoGeneratedCode}
                      </Badge>
                    )}
                  </TableCell>
                  <TableCell>
                    {centre.currentCode !== centre.autoGeneratedCode && (
                      <Badge variant="outline" className="font-mono text-sm">
                        {centre.autoGeneratedCode}
                      </Badge>
                    )}
                  </TableCell>
                  <TableCell className="text-right">
                    {editingId === centre.id ? (
                      <div className="flex justify-end gap-2">
                        <Button
                          size="sm"
                          onClick={() => handleSave(centre.id)}
                          disabled={updateCode.isPending}
                        >
                          {updateCode.isPending ? (
                            <Loader2 className="h-4 w-4 animate-spin" />
                          ) : (
                            <Check className="h-4 w-4" />
                          )}
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={handleCancel}
                          disabled={updateCode.isPending}
                        >
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    ) : (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handleEdit(centre)}
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {centres?.length === 0 && (
            <div className="text-center py-12 text-muted-foreground">
              No shopping centres found
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="mt-6">
        <CardHeader>
          <CardTitle>Code Format Rules</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-muted-foreground">
          <p>• Codes must be exactly <strong>4 uppercase letters</strong> (A-Z)</p>
          <p>• Each code must be <strong>unique</strong> across all centres</p>
          <p>• Codes are used in booking numbers: <code className="bg-muted px-1 py-0.5 rounded">CODE-YYYYMMDD-SEQ</code></p>
          <p>• Example: <code className="bg-muted px-1 py-0.5 rounded">CAMA-20260601-001</code> for Campbelltown Mall</p>
          <p className="pt-2">
            <strong>Auto-generated codes</strong> are created from centre names:
          </p>
          <ul className="list-disc list-inside pl-4 space-y-1">
            <li>"Campbelltown Mall" → <code className="bg-muted px-1 py-0.5 rounded">CAMA</code></li>
            <li>"Highlands Marketplace" → <code className="bg-muted px-1 py-0.5 rounded">HIMA</code></li>
            <li>"Westfield Parramatta" → <code className="bg-muted px-1 py-0.5 rounded">WEPA</code></li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}
